apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Svc.Cronjob.name }}
spec:
  selector:
    app: {{ .Values.Svc.Cronjob.name }}
  ports:
    - port: {{ .Values.Svc.Cronjob.port }}  
      targetPort: {{ .Values.Svc.Cronjob.target_port }}
  type: {{ .Values.Svc.type }}
